//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionTests.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBConnectionTests.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @V_MainName SYSNAME = &apos;{0}&apos;;
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_LoginName SYSNAME = &apos;L_&apos; + @V_MainName;
        ///DECLARE @V_SchemaName SYSNAME = &apos;S_&apos; + @V_MainName;
        ///DECLARE @V_UserName SYSNAME = &apos;U_&apos; + @V_MainName;
        ///DECLARE @V_QueueName SYSNAME = &apos;Q_&apos; + @V_MainName;
        ///DECLARE @V_ServiceName SYSNAME = &apos;Service&apos; + @V_MainName;
        ///
        ///-- Uninstall all triggers
        ///DECLARE @V_TriggerName SYSNAME ;
        ///DECLARE CU_TriggersCursor CURSOR FOR
        ///	SELECT TBL_Triggers.name
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminInstall_Cleanup {
            get {
                return ResourceManager.GetString("AdminInstall_Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @V_MainName SYSNAME = &apos;{0}&apos;;
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_LoginName SYSNAME = &apos;L_&apos; + @V_MainName;
        ///DECLARE @V_SchemaName SYSNAME = &apos;S_&apos; + @V_MainName;
        ///DECLARE @V_UserName SYSNAME = &apos;U_&apos; + @V_MainName;
        ///DECLARE @V_QueueName SYSNAME = &apos;Q_&apos; + @V_MainName;
        ///DECLARE @V_ServiceName SYSNAME = &apos;Service&apos; + @V_MainName;
        ///
        ///IF 
        ///	EXISTS (
        ///		SELECT name
        ///		FROM sys.routes
        ///		WHERE name = &apos;AutoCreatedLocal&apos;
        ///	)
        ///	AND
        ///	EXISTS (
        ///		SELECT name
        ///		FROM [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminInstall_Test {
            get {
                return ResourceManager.GetString("AdminInstall_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @V_MainName SYSNAME = &apos;{0}&apos;;
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///-- Drop Type
        ///IF EXISTS (
        ///		SELECT column1 
        ///		FROM dbo.TBL_TestTable)
        ///	BEGIN
        ///		SELECT 1
        ///	END
        ///ELSE
        ///	BEGIN
        ///		SELECT 0
        ///	END.
        /// </summary>
        public static string AdminInstallObservedShema_Test {
            get {
                return ResourceManager.GetString("AdminInstallObservedShema_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @V_MainName SYSNAME = &apos;{0}&apos;;
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_LoginName SYSNAME = &apos;L_&apos; + @V_MainName;
        ///DECLARE @V_SchemaName SYSNAME = &apos;S_&apos; + @V_MainName;
        ///DECLARE @V_UserName SYSNAME = &apos;U_&apos; + @V_MainName;
        ///DECLARE @V_QueueName SYSNAME = &apos;Q_&apos; + @V_MainName;
        ///DECLARE @V_ServiceName SYSNAME = &apos;Service&apos; + @V_MainName;
        ///
        ///-- Drop Type
        ///IF NOT EXISTS(
        ///		SELECT SysTables.name
        ///		FROM sys.tables AS SysTables
        ///		INNER JOIN sys.schemas AS SysSchemas
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminUnInstall_Test {
            get {
                return ResourceManager.GetString("AdminUnInstall_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @V_MainName SYSNAME = &apos;{0}&apos;;
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///
        ///DECLARE @V_ReferencedSchema SYSNAME = &apos;{1}&apos;;
        ///DECLARE @V_ReferencedTable SYSNAME = &apos;{2}&apos;;
        ///
        ///SET @V_Cmd = &apos;
        ///	UPDATE &apos; + QUOTENAME( @V_ReferencedSchema ) + &apos;.&apos; + QUOTENAME( @V_ReferencedTable ) + &apos;
        ///	SET column1 = 2
        ///	WHERE column1 is null ;
        ///	&apos;
        ///
        ///EXECUTE ( @V_Cmd ) ;.
        /// </summary>
        public static string SqlProcedures_ChangeData {
            get {
                return ResourceManager.GetString("SqlProcedures_ChangeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @V_MainName SYSNAME = &apos;{0}&apos;;
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_LoginName SYSNAME = &apos;L_&apos; + @V_MainName;
        ///DECLARE @V_SchemaName SYSNAME = &apos;S_&apos; + @V_MainName;
        ///DECLARE @V_UserName SYSNAME = &apos;U_&apos; + @V_MainName;
        ///DECLARE @V_QueueName SYSNAME = &apos;Q_&apos; + @V_MainName;
        ///DECLARE @V_ServiceName SYSNAME = &apos;Service&apos; + @V_MainName;
        ///DECLARE @V_TableName SYSNAME = &apos;TBL_Subscribers&apos; ;
        ///
        ///DECLARE @V_SubscriberString VARCHAR(max) = &apos;{1}&apos;;
        ///DECLARE @V_SubscriptionH [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SqlProcedures_InstallSubscription {
            get {
                return ResourceManager.GetString("SqlProcedures_InstallSubscription", resourceCulture);
            }
        }
    }
}
