//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionTests.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBConnectionTests.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON;
        ///SET QUOTED_IDENTIFIER ON;
        ///SET NOCOUNT ON; 
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos; ;
        ///DECLARE @V_MainName SYSNAME = &apos;{1}&apos; ;
        ///DECLARE @V_LoginName SYSNAME = &apos;{2}&apos; ;
        ///DECLARE @V_SchemaName SYSNAME = &apos;{3}&apos; ;
        ///DECLARE @V_UserName SYSNAME = &apos;{4}&apos; ;
        ///DECLARE @V_QueueName SYSNAME = &apos;{5}&apos; ;
        ///DECLARE @V_ServiceName SYSNAME = &apos;{6}&apos; ;
        ///DECLARE @V_SubscribersTableName SYSNAME = &apos;{7}&apos; ;
        ///DECLARE @V_ParametersTypeName SYSNAME = &apos;TYPE_ParametersType&apos;;
        ///DECLARE @V_InstallP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminInstall_Test {
            get {
                return ResourceManager.GetString("AdminInstall_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON;
        ///SET QUOTED_IDENTIFIER ON;
        ///SET NOCOUNT ON; 
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos; ;
        ///DECLARE @V_MainName SYSNAME = &apos;{1}&apos; ;
        ///DECLARE @V_LoginName SYSNAME = &apos;{2}&apos; ;
        ///DECLARE @V_SchemaName SYSNAME = &apos;{3}&apos; ;
        ///DECLARE @V_UserName SYSNAME = &apos;{4}&apos; ;
        ///DECLARE @V_QueueName SYSNAME = &apos;{5}&apos; ;
        ///DECLARE @V_ServiceName SYSNAME = &apos;{6}&apos; ;
        ///DECLARE @V_SubscribersTableName SYSNAME = &apos;{7}&apos; ;
        ///DECLARE @V_ParametersTypeName SYSNAME = &apos;TYPE_ParametersType&apos;;
        ///DECLARE @V_InstallP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminUnInstall_Test {
            get {
                return ResourceManager.GetString("AdminUnInstall_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos;;
        ///
        ///-- drop DB
        ///SET @V_Cmd = &apos;
        ///	DROP DATABASE IF EXISTS &apos; + QUOTENAME( @V_DBName ) + &apos; ; 
        ///&apos; ;
        ///EXEC ( @V_Cmd );
        ///
        ///-- create DB
        ///SET @V_Cmd = &apos;
        ///	CREATE DATABASE &apos; + QUOTENAME( @V_DBName ) + &apos; ; 
        ///&apos; ;
        ///EXEC ( @V_Cmd );
        ///
        ///-- switch to DB
        ///SET @V_Cmd = &apos;
        ///	USE &apos; + QUOTENAME( @V_DBName ) + &apos; ; 
        ///&apos; ;
        ///EXEC ( @V_Cmd );
        ///
        ///-- create two tables
        ///CREATE TABLE [dbo].[TBL_FirstTable] (
        ///    [C_ID] INT  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SetEmptyDB {
            get {
                return ResourceManager.GetString("SetEmptyDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON;
        ///SET QUOTED_IDENTIFIER ON;
        ///SET NOCOUNT ON; 
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos; ;
        ///DECLARE @V_MainName SYSNAME = &apos;{1}&apos; ;
        ///DECLARE @V_LoginName SYSNAME = &apos;{2}&apos; ;
        ///DECLARE @V_SchemaName SYSNAME = &apos;{3}&apos; ;
        ///DECLARE @V_UserName SYSNAME = &apos;{4}&apos; ;
        ///DECLARE @V_QueueName SYSNAME = &apos;{5}&apos; ;
        ///DECLARE @V_ServiceName SYSNAME = &apos;{6}&apos; ;
        ///DECLARE @V_SubscribersTableName SYSNAME = &apos;{7}&apos; ;
        ///DECLARE @V_ParametersTypeName SYSNAME = &apos;TYPE_ParametersType&apos;;
        ///DECLARE @V_InstallP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SetSubscription_Test {
            get {
                return ResourceManager.GetString("SetSubscription_Test", resourceCulture);
            }
        }
    }
}
