//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnection.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBConnection.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos; ;
        ///DECLARE @V_MainName SYSNAME = &apos;{1}&apos; ;
        ///DECLARE @V_ObservedSchemaName SYSNAME = &apos;{2}&apos; ;
        ///
        ///-- switch to DB
        ///USE [{0}];
        ///
        ///DECLARE @V_UserName SYSNAME = @V_MainName;
        ///
        ///-- switch to DB
        ///SET @V_Cmd = &apos;
        ///	USE &apos; + QUOTENAME( @V_DBName ) + &apos; ; 
        ///&apos; ;
        ///EXEC ( @V_Cmd );
        ///
        ///-- grant
        ///SET @V_Cmd = &apos;
        ///	GRANT ALTER ON SCHEMA::&apos; + QUOTENAME( @V_ObservedSchemaName ) + &apos; TO &apos; + QUOTENAME(@V_UserName)  + &apos;;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminAddObservedShema {
            get {
                return ResourceManager.GetString("AdminAddObservedShema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos; ;
        ///DECLARE @V_MainName SYSNAME = &apos;{1}&apos; ;
        ///DECLARE @V_Password NVARCHAR(max) = &apos;{2}&apos; ;
        ///DECLARE @V_InstallSubscriptionProcedureBody NVARCHAR(max) = &apos;{3}&apos;;
        ///DECLARE @V_ReceiveSubscriptionProcedureBody NVARCHAR(max) = &apos;{4}&apos;;
        ///DECLARE @V_UninstallSubscriptionProcedureBody NVARCHAR(max) = &apos;{5}&apos;;
        ///
        ///-- switch to DB
        ///USE [{0}];
        ///
        ///-- test requirements 
        ///DECLARE @V_CompatibilityLvl int = 0 ;
        ///DECLARE @V [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminInstall {
            get {
                return ResourceManager.GetString("AdminInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos; ;
        ///DECLARE @V_MainName SYSNAME = &apos;{1}&apos; ;
        ///DECLARE @V_ObservedSchemaName SYSNAME = &apos;{2}&apos; ;
        ///
        ///-- switch to DB
        ///USE [{0}];
        ///
        ///DECLARE @V_UserName SYSNAME = @V_MainName;
        ///
        ///-- switch to DB
        ///SET @V_Cmd = &apos;
        ///	USE &apos; + QUOTENAME( @V_DBName ) + &apos; ; 
        ///&apos; ;
        ///EXEC ( @V_Cmd );
        ///
        ///-- revoke
        ///SET @V_Cmd = &apos;
        ///	REVOKE ALTER ON SCHEMA::&apos; + QUOTENAME( @V_ObservedSchemaName ) + &apos; TO &apos; + QUOTENAME(@V_UserName)  + &apos;; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminRemoveObservedShema {
            get {
                return ResourceManager.GetString("AdminRemoveObservedShema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///DECLARE @V_Cmd NVARCHAR(max);
        ///SET ANSI_NULLS ON
        ///SET QUOTED_IDENTIFIER ON
        ///
        ///DECLARE @V_DBName SYSNAME = &apos;{0}&apos; ;
        ///DECLARE @V_MainName SYSNAME = &apos;{1}&apos; ;
        ///DECLARE @V_LoginName SYSNAME = @V_MainName ;
        ///DECLARE @V_SchemaName SYSNAME = @V_MainName ;
        ///DECLARE @V_UserName SYSNAME = @V_MainName ;
        ///DECLARE @V_QueueName SYSNAME = &apos;Q_&apos; + @V_MainName ;
        ///DECLARE @V_ServiceName SYSNAME = &apos;S_&apos; + @V_MainName ;
        ///DECLARE @V_SubscribersTableName SYSNAME = &apos;TBL_SubscribersTable&apos; ;
        ///DECLARE @V_ParametersTypeName SYSNAME = &apos;T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AdminUninstall {
            get {
                return ResourceManager.GetString("AdminUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [&lt;3&gt;].[P_InstallSubscription]
        ///	@V_SubscriberString NVARCHAR(200),
        ///	@V_SubscriptionHash INT,
        ///	@V_ProcedureSchemaName SYSNAME,
        ///	@V_ProcedureName SYSNAME,
        ///	@TBL_ProcedureParameters dbo.TYPE_ParametersType READONLY,
        ///	@V_NotificationValidFor INT = 432000 -- 5 days to receive notification
        ///AS 
        ///BEGIN
        ///	
        ///	DECLARE @V_Cmd NVARCHAR(max);
        ///	SET ANSI_NULLS ON;
        ///	SET QUOTED_IDENTIFIER ON;
        ///	SET NOCOUNT ON; 
        ///
        ///	DECLARE @V_DBName SYSNAME = &apos;&lt;0&gt;&apos; ;
        ///	DECLARE @V_MainName SYSNAME = &apos;&lt;1&gt;&apos; ;
        ///	DECLARE  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string P_InstallSubscription {
            get {
                return ResourceManager.GetString("P_InstallSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [&lt;3&gt;].[P_ReceiveSubscription]
        ///	@V_ReceiveTimeout int = 150000 -- After 5 min retry getting message from queue.
        ///AS 
        ///BEGIN
        ///
        ///	DECLARE @V_Cmd NVARCHAR(max);
        ///	SET ANSI_NULLS ON;
        ///	SET QUOTED_IDENTIFIER ON;
        ///	SET NOCOUNT ON; 
        ///
        ///	DECLARE @V_DBName SYSNAME = &apos;&lt;0&gt;&apos; ;
        ///	DECLARE @V_MainName SYSNAME = &apos;&lt;1&gt;&apos; ;
        ///	DECLARE @V_LoginName SYSNAME = &apos;&lt;2&gt;&apos; ;
        ///	DECLARE @V_SchemaName SYSNAME = &apos;&lt;3&gt;&apos; ;
        ///	DECLARE @V_UserName SYSNAME = &apos;&lt;4&gt;&apos; ;
        ///	DECLARE @V_QueueName SYSNAME = &apos;&lt;5&gt;&apos; ;
        ///	DECLARE @V_ServiceName  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string P_ReceiveSubscription {
            get {
                return ResourceManager.GetString("P_ReceiveSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [&lt;3&gt;].[P_UninstallSubscription]
        ///	@V_SubscriberString NVARCHAR(200) = null,
        ///	@V_SubscriptionHash INT = null,
        ///	@V_ProcedureSchemaName SYSNAME = null,
        ///	@V_ProcedureName SYSNAME = null,
        ///	@TBL_ProcedureParameters dbo.TYPE_ParametersType READONLY,
        ///	@V_NotificationValidFor INT = 432000 -- 5 days to receive notification
        ///AS
        ///BEGIN
        ///
        ///	DECLARE @V_Cmd NVARCHAR(max);
        ///	SET ANSI_NULLS ON;
        ///	SET QUOTED_IDENTIFIER ON;
        ///	SET NOCOUNT ON; 
        ///
        ///	DECLARE @V_DBName SYSNAME = &apos;&lt;0&gt;&apos; ;
        ///	DECLARE @V_MainName  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string P_UninstallSubscription {
            get {
                return ResourceManager.GetString("P_UninstallSubscription", resourceCulture);
            }
        }
    }
}
