GRANT VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO PUBLIC;


GO
GRANT VIEW ANY COLUMN MASTER KEY DEFINITION TO PUBLIC;


GO
GRANT CONNECT TO [U_DependencyDB];


GO
GRANT SUBSCRIBE QUERY NOTIFICATIONS TO [U_DependencyDB];


GO
GRANT CONTROL
    ON CONTRACT::[DEFAULT] TO [U_DependencyDB];

